import type { Metadata } from "next";
import "./globals.css";

interface Props {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
